files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/ULSWAPDAQ2
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 43D6ADA064E6551F1B518951A26C6F64
  logicalPath: config/ULSWAPDAQ2
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 43D6ADA064E6551F1B518951A26C6F64
- generatedChecksum: EFD2F96D013C2C17C6B2380A49876793
  logicalPath: config/ULSWAPDAQ2
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: EFD2F96D013C2C17C6B2380A49876793
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: A5537A3FD05521C9755D57EF565D812A
  logicalPath: config/ULSWAPDAQ2/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: A5537A3FD05521C9755D57EF565D812A
- generatedChecksum: 7CF1B38C4CBC41C5E905398700D9EE3B
  logicalPath: config/ULSWAPDAQ2/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7CF1B38C4CBC41C5E905398700D9EE3B
- generatedChecksum: A768A018692EACDD0D07871BC07651AD
  logicalPath: config/ULSWAPDAQ2/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: A768A018692EACDD0D07871BC07651AD
- generatedChecksum: 182BCBFDDC166894717417258B6754A9
  logicalPath: config/ULSWAPDAQ2/peripheral/spi/spi_master
  name: plib_spi1_master.c
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: 182BCBFDDC166894717417258B6754A9
- generatedChecksum: 5C98947D97A9F4DC29747CE7783020FF
  logicalPath: config/ULSWAPDAQ2/peripheral/tmr1
  name: plib_tmr1.c
  physicalPath: peripheral/tmr1
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5C98947D97A9F4DC29747CE7783020FF
- generatedChecksum: B94FFA232CEBDBC4A1DB017BCC0F012F
  logicalPath: config/ULSWAPDAQ2/peripheral/tmr
  name: plib_tmr2.c
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: B94FFA232CEBDBC4A1DB017BCC0F012F
- generatedChecksum: 78D882820F55A497D8EE7262E1184A3F
  logicalPath: config/ULSWAPDAQ2/peripheral/uart
  name: plib_uart1.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 78D882820F55A497D8EE7262E1184A3F
- generatedChecksum: 42A948E504602741B0D592C55FCD9A7B
  logicalPath: config/ULSWAPDAQ2/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 42A948E504602741B0D592C55FCD9A7B
- generatedChecksum: FC1B6011BFB1342E761831E9C1016A17
  logicalPath: config/ULSWAPDAQ2
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FC1B6011BFB1342E761831E9C1016A17
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/ULSWAPDAQ2
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/ULSWAPDAQ2
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/ULSWAPDAQ2/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: A2CC849C687144A046545E8CF6188343
  logicalPath: config/ULSWAPDAQ2/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: A2CC849C687144A046545E8CF6188343
- generatedChecksum: 456CD7FA3A9BAD70FA3D0C8E4ECB0787
  logicalPath: config/ULSWAPDAQ2/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 456CD7FA3A9BAD70FA3D0C8E4ECB0787
- generatedChecksum: A9C21E81CB403E638EEB811A7780088B
  logicalPath: config/ULSWAPDAQ2/peripheral/spi/spi_master
  name: plib_spi1_master.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: A9C21E81CB403E638EEB811A7780088B
- generatedChecksum: CFA758C8B7258190473EF7C60C4BA4E9
  logicalPath: config/ULSWAPDAQ2/peripheral/spi/spi_master
  name: plib_spi_master_common.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: CFA758C8B7258190473EF7C60C4BA4E9
- generatedChecksum: 32D7539D9231F3C159ABECE91A0281EA
  logicalPath: config/ULSWAPDAQ2/peripheral/tmr1
  name: plib_tmr1.h
  physicalPath: peripheral/tmr1
  security: NON_SECURE
  type: HEADER
  userChecksum: 32D7539D9231F3C159ABECE91A0281EA
- generatedChecksum: 69E7C8CDAB1B32838331EE261170CEA4
  logicalPath: config/ULSWAPDAQ2/peripheral/tmr1
  name: plib_tmr1_common.h
  physicalPath: peripheral/tmr1
  security: NON_SECURE
  type: HEADER
  userChecksum: 69E7C8CDAB1B32838331EE261170CEA4
- generatedChecksum: 612994C7F3C27F2CFA2621C1F65D4068
  logicalPath: config/ULSWAPDAQ2/peripheral/tmr
  name: plib_tmr2.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: 612994C7F3C27F2CFA2621C1F65D4068
- generatedChecksum: D948F2CE092CAB556EF299D3CCD83A55
  logicalPath: config/ULSWAPDAQ2/peripheral/tmr
  name: plib_tmr_common.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D948F2CE092CAB556EF299D3CCD83A55
- generatedChecksum: 991F2B1F3EA07254B6A9C096A3CDDFD6
  logicalPath: config/ULSWAPDAQ2/peripheral/uart
  name: plib_uart1.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 991F2B1F3EA07254B6A9C096A3CDDFD6
- generatedChecksum: 91611515A95D92B82B7F4064C16D122B
  logicalPath: config/ULSWAPDAQ2/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 91611515A95D92B82B7F4064C16D122B
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/ULSWAPDAQ2
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: 52AA20E8BAA488B3B6581379249C0FCE
  logicalPath: config/ULSWAPDAQ2
  name: p32MX470F512H.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 52AA20E8BAA488B3B6581379249C0FCE
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/ULSWAPDAQ2;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/ULSWAPDAQ2;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
