configName: ULSWAPDAQ2
folderName: ULSWAPDAQ2
format_version: v1.0
frameworkPath: ..\..\Harmony3
processor: PIC32MX470F512H
projectName: ULSWAPDAQ2
settings:
  PackageFilter: bsp;core;core_apps_pic32mx;csp;csp_apps_pic32mx;dev_packs;harmony-services;quick_docs;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\PIC32MX_DFP\1.5.259\atdf\PIC32MX470F512H.atdf
