format_version: v1.0
type: UniqueComponent
attributes: {id: tmr1}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TIMER1_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr1, value: '48000000'}
  - type: Long
    attributes: {id: TIMER1_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr1, value: '0'}
  - type: Float
    attributes: {id: TIMER1_TIME_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: Float
        attributes: {id: max}
        children:
        - {type: Value, value: '1365354.1'}
    - type: Values
      children:
      - type: User
        attributes: {value: '1.0'}
  - type: Combo
    attributes: {id: TIMER_UNIT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: nanosecond}
  - type: Boolean
    attributes: {id: TMR1_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '30', y: '60', id: tmr1}
